name: flutter3_core
description: flutter3 core package
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

# https://pub.dev/packages/isar
isar_version: &isar_version ^3.1.0+1
# https://pub.dev/packages/hive
hive_version: &hive_version ^2.2.3

# https://dart.dev/tools/pub/workspaces/
# Support for pub workspaces was introduced in Dart 3.6.0.
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter3_res:
    path: ../flutter3_res
  flutter3_basics:
    path: ../flutter3_basics
  flutter3_widgets:
    path: ../flutter3_widgets
  flutter3_http:
    path: ../flutter3_http
  flutter3_vector:
    path: ../flutter3_vector

  # https://pub.dev/packages/cross_file # meta, web
  # https://github.com/flutter/packages/tree/main/packages/cross_file
  # https://pub.dev/packages/js
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/web
  cross_file: ^0.3.4+2
  # https://pub.dev/packages/web
  # mobile_scanner ^5.1.1 requires web ^0.5.1.
  web: ^1.1.1

  # https://pub.dev/packages/path_provider
  # https://github.com/flutter/packages/tree/main/packages/path_provider/path_provider
  path_provider: ^2.1.5

  # https://pub.dev/packages/path
  # https://github.com/dart-lang/path
  # path is pinned to version 1.9.0 by flutter_test from the flutter SDK.
  path: ^1.9.1

  # https://pub.dev/packages/mime
  # https://github.com/dart-lang/mime
  # shelf_multipart 2.0.0 depends on mime ^1.0.0
  # Because flutter_oss_aliyun 6.4.2 depends on mime ^1.0.4 and no versions of flutter_oss_aliyun match >6.4.2 <7.0.0, flutter_oss_aliyun ^6.4.2 requires mime ^1.0.4.
  # So, because flutter3_core depends on mime ^2.0.0 and flutter3_oss depends on flutter_oss_aliyun ^6.4.2, version solving failed.
  mime: ^1.0.6

  # https://pub.dev/packages/filesize
  # https://github.com/synw/filesize
  #filesize: ^2.0.1

  # https://pub.dev/packages/provider
  # https://github.com/rrousselGit/provider
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/nested
  provider: ^6.1.5

  # https://pub.dev/packages/jetpack
  # https://github.com/praja/jetpack
  # https://pub.dev/packages/provider
  #jetpack: ^1.0.4

  # https://pub.dev/packages/objectbox
  # https://docs.objectbox.io/getting-started
  # https://github.com/objectbox/objectbox-dart
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/flat_buffers
  # https://pub.dev/packages/ffi
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/path
  #objectbox: ^2.3.1

  # https://pub.dev/packages/isar
  # https://github.com/isar/isar
  # https://pub.dev/packages/analyzer
  # https://github.com/dart-lang/sdk/tree/main/pkg/analyzer
  # https://pub.dev/packages/ffi
  # https://pub.dev/packages/js
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/source_gen
  # https://isar.dev/zh/tutorials/quickstart.html
  isar: *isar_version

  # https://pub.dev/packages/isar_flutter_libs
  # https://github.com/isar/isar/tree/main/packages/isar_flutter_libs
  isar_flutter_libs: *isar_version

  # https://pub.dev/packages/hive
  # https://github.com/isar/hive
  # https://pub.dev/packages/isar
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/hive_generator
  hive: *hive_version

  # https://pub.dev/packages/hive_flutter
  # https://github.com/hivedb/hive_flutter
  # https://pub.dev/packages/hive
  # https://pub.dev/packages/path_provider
  # https://pub.dev/packages/path
  hive_flutter: ^1.1.0

# dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  #isar_generator: *isar_version
  flutter_isar_generator_fixed: ^0.0.2
  #hive_generator: ^2.0.1
  #flutter_hive_generator_fixed: ^0.0.2
  build_runner: any
  flutter_gen_runner: any
  json_serializable: any

# https://pub.dev/packages/flutter_gen
# https://github.com/FlutterGen/flutter_gen
# https://pub.dev/packages/flutter_gen#configuration-file
# https://pub.dev/packages/flutter_gen
# https://pub.dev/packages/build_runner
# https://pub.dev/packages/flutter_gen_runner
flutter_gen:
  output: lib/assets_generated/ # Optional (default: lib/gen/)
  parse_metadata: true
  assets:
    outputs:
      package_parameter_enabled: true
      directory_path_enabled: true
  integrations:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/png/
    - assets/svg/

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
