name: flutter3_code
description: "flutter3 qr code / bar code / scanner project."
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter3_basics:
    path: ../flutter3_basics

  # https://pub.dev/packages/qr
  # 用于 Dart 和 Flutter 的二维码生成库。
  # https://github.com/kevmoo/qr.dart
  # https://pub.dev/packages/meta
  # https://kevmoo.github.io/qr.dart/
  qr: ^3.0.2

  # https://pub.dev/packages/barcode
  # Dart 的条形码生成库，可以为任何后端生成通用绘图操作。
  # https://github.com/DavBfr/dart_barcode
  # https://pub.dev/packages/qr
  # https://pub.dev/packages/meta
  barcode: ^2.2.8

  # https://pub.dev/packages/barcode_image
  # Dart 的条形码生成库，可以使用 pub:image 库生成条形码。
  # https://davbfr.github.io/dart_barcode/
  # https://pub.dev/packages/args
  # https://pub.dev/packages/barcode
  # https://pub.dev/packages/image
  # https://pub.dev/packages/meta
  barcode_image: ^2.0.3
  # https://pub.dev/packages/image
  # https://pub.dev/packages/archive
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/xml
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

  # https://pub.dev/packages/qr_flutter
  # QR.Flutter 是一个 Flutter 库，用于通过 Widget 或自定义 Painter 进行简单快速的 QR 代码渲染。
  # https://pub.dev/packages/qr
  qr_flutter: ^4.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
