name: flutter3_app
description: flutter3 app package
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=1.17.0"

# https://dart.dev/tools/pub/workspaces/
# Support for pub workspaces was introduced in Dart 3.6.0.
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter3_res:
    path: ../flutter3_res
  flutter3_basics:
    path: ../flutter3_basics
  flutter3_core:
    path: ../flutter3_core
  flutter3_http:
    path: ../flutter3_http
  flutter3_pub:
    path: ../flutter3_pub

  # https://pub.dev/packages/package_info_plus
  # https://github.com/fluttercommunity/plus_plugins/tree/main/packages/package_info_plus/package_info_plus
  # https://pub.dev/packages/ffi
  # https://pub.dev/packages/http
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/path
  # https://pub.dev/packages/package_info_plus_platform_interface
  # https://pub.dev/packages/web
  # https://pub.dev/packages/win32
  package_info_plus: ^8.3.0

  # https://pub.dev/packages/device_info_plus
  # https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus/device_info_plus
  # https://pub.dev/packages/device_info_plus_platform_interface
  # https://pub.dev/packages/ffi
  # https://pub.dev/packages/file
  # https://pub.dev/packages/flutter_web_plugins
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/win32
  # https://pub.dev/packages/win32_registry
  device_info_plus: ^11.4.0

  # https://pub.dev/packages/share_plus
  # https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus
  # https://pub.dev/packages/cross_file
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/mime
  # https://pub.dev/packages/share_plus_platform_interface
  # https://pub.dev/packages/file
  # https://pub.dev/packages/ffi
  # https://pub.dev/packages/win32
  share_plus: ^11.0.0

  # https://pub.dev/packages/flutter_local_notifications
  # https://github.com/MaikuB/flutter_local_notifications
  # https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications
  # https://pub.dev/packages/clock
  # https://pub.dev/packages/flutter_local_notifications_linux
  # https://pub.dev/packages/flutter_local_notifications_platform_interface
  # https://pub.dev/packages/timezone
  # ANDROID IOS LINUX MACOS
  flutter_local_notifications: ^19.1.0

  # https://pub.dev/packages/flutter_animate
  # https://github.com/gskinner/flutter_animate
  flutter_animate: ^4.5.2

  # 权限处理插件
  # https://pub.dev/packages/permission_handler
  # https://github.com/baseflow/flutter-permission-handler
  # https://pub.dev/packages/meta
  permission_handler: ^11.3.1 #ANDROID IOS WEB WINDOWS

  # 保存图片到相册
  # https://pub.dev/packages/image_gallery_saver
  # https://github.com/hui-z/image_gallery_saver
  #image_gallery_saver: ^2.0.3 #ANDROID IOS
  # https://pub.dev/packages/image_gallery_saver_plus
  # https://github.com/ArmanKT/image_gallery_saver_plus
  image_gallery_saver_plus: ^4.0.1 #ANDROID IOS

  # https://pub.dev/packages/flutter_install_app
  # flutter_install_app: ^1.3.0 #ANDROID IOS

  # https://pub.dev/packages/flutter_android_package_installer
  # https://github.com/FlutterStudioIst/android_package_installer
  flutter_android_package_installer: ^0.0.2+3

  # https://pub.dev/packages/receive_sharing_intent_plus
  receive_sharing_intent_plus: #^1.0.1
    git: git@github.com:angcyo/receive_sharing_intent_plus.git
  # https://pub.dev/packages/uri_to_file
  uri_to_file: ^1.0.0

  # https://pub.dev/packages/flutter_move_task_back
  # flutter_move_task_back: ^1.0.0 #ANDROID
  flutter_move_task_back:
    git: git@github.com:angcyo/flutter_move_task_back.git

dependency_overrides:
#cross_file: ^0.3.4+1
#web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  # https://pub.dev/packages/flutter_gen_runner
  flutter_gen_runner: any
  json_serializable: any

# https://pub.dev/packages/flutter_gen#configuration-file
# dart run build_runner build --delete-conflicting-outputs
# flutter pub run build_runner build
flutter_gen:
  output: lib/assets_generated/ # Optional (default: lib/gen/)
  parse_metadata: true
  assets:
    outputs:
      package_parameter_enabled: true
      directory_path_enabled: true
  integrations:
  #flutter_svg: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/svg/
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
