name: flutter3_pub
description: flutter3 pub package
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter3_basics:
    path: ../flutter3_basics
  # https://pub.dev/packages/cached_network_image
  # https://pub.dev/packages/flutter_cache_manager
  # https://pub.dev/packages/octo_image
  cached_network_image: ^3.3.0

  # https://pub.dev/packages/flutter_html
  # https://pub.dev/packages/html
  # https://pub.dev/packages/csslib
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/list_counter
  flutter_html: ^3.0.0-beta.2

  # https://pub.dev/packages/flutter_svg
  # https://github.com/dnfield/flutter_svg/tree/master/packages/flutter_svg
  # https://pub.dev/packages/vector_graphics
  # https://pub.dev/packages/vector_graphics_codec
  # https://pub.dev/packages/vector_graphics_compiler
  flutter_svg: ^2.0.9

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.1

  # https://pub.dev/packages/file_picker
  # https://github.com/miguelpruivo/flutter_file_picker
  # https://pub.dev/packages/flutter_plugin_android_lifecycle
  # https://pub.dev/packages/plugin_platform_interface
  # https://pub.dev/packages/path
  # https://pub.dev/packages/win32
  file_picker: ^6.1.1

# dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
