name: flutter3_http
description: flutter3 http package
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter3_basics:
    path: ../flutter3_basics
  # https://pub.dev/packages/http
  # https://pub.dev/packages/async
  # https://pub.dev/packages/http_parser
  http: ^1.2.2
  # https://pub.dev/packages/dio
  # https://pub.dev/packages/async
  # https://pub.dev/packages/http_parser
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/path
  dio: ^5.6.0
  # https://pub.dev/packages/dio_http2_adapter
  # https://pub.dev/packages/http2
  # https://pub.dev/packages/dio
  #dio_http2_adapter: ^2.3.2
  # https://pub.dev/packages/json_annotation
  # https://github.com/google/json_serializable.dart/tree/master/json_annotation
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  # https://pub.dev/packages/json_serializable
  # https://github.com/google/json_serializable.dart/tree/master/json_serializable
  # https://pub.dev/packages/analyzer
  # https://pub.dev/packages/async
  # https://pub.dev/packages/build
  # https://pub.dev/packages/build_config
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/json_annotation
  # https://pub.dev/packages/meta
  # https://pub.dev/packages/path
  # https://pub.dev/packages/pub_semver
  # https://pub.dev/packages/pubspec_parse
  # https://pub.dev/packages/source_gen
  # https://pub.dev/packages/source_helper
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
