name: flutter3_excel
description: "flutter excel package."
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

# https://dart.dev/tools/pub/workspaces/
# Support for pub workspaces was introduced in Dart 3.6.0.
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter3_basics:
    path: ../flutter3_basics

  # https://pub.dev/packages/excel
  # https://pub.dev/packages/archive
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/equatable
  # https://pub.dev/packages/xml
  # excel: ^4.0.3 //读取wps的xlsx有bug Exception: custom numFmtId starts at 164 but found a value of 41
  #excel_dart: ^3.0.0
  #And because excel >=4.0.6 depends on archive ^3.6.1, every version of flutter3_abc from path requires archive ^3.6.1.
  #excel: ^4.0.6
  excel:
    git:
      url: git@github.com:FlutterStudioIst/excel.git
      ref: 4.0.6-fix2

dependency_overrides:
  # in flutter3_pub
  # archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
